version: '3.7'

services:
    nextjs:
        container_name: nextjs

        build: ./nextjs

        command: npm run dev

        volumes:
            - ./nextjs:/usr/src/nextjs

        ports:
            - 3000:3000

        depends_on:
          - django

    django:
        container_name: django

        build: ./django

        command: python -u manage.py runserver 0.0.0.0:8000

        volumes:
            - ./django:/usr/src/django

        environment:
            # 1ならデバックモード
            - DEBUG=1
            # setting.pyに記載されているSECRET_KEYを記入
            - SECRET_KEY=django-insecure--w@!)fvdh72o8-wuwpa_(c00g(ew4t-t*#ghk+uwn^n%0fhce6

        ports:
            - 8000:8000
