version: '3.7'

services:
    django:
            container_name: django

            build:
                context: ./django
                dockerfile: ./Dockerfile.build

            command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input --clear && uwsgi --socket :8001 --module config.wsgi --py-autoreload 1 -b 32768"

            volumes:
                - ./django:/usr/src/django
                - django_static:/usr/src/django/static
                - django_media:/usr/src/django/media

            env_file:
            - django-docker-compose.env


            expose:
                - "8001"

    nextjs:
        container_name: nextjs

        build:
            context: ./nextjs
            dockerfile: ./Dockerfile.build

        command: bash -c "npm run build && npm run start"

        volumes:
            - ./nextjs:/usr/src/nextjs

        depends_on:
            - django
            - nextjs-nginx

    django-nginx:
        container_name: django-nginx

        build: ./django-nginx

        ports:
            - 80:80

        volumes:
            - ./django-nginx/conf:/etc/nginx/conf.d
            - ./django-nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - django_static:/usr/src/django/static
            - django_media:/usr/src/django/media

        depends_on:
            - django

    nextjs-nginx:
        container_name: nextjs-nginx

        build: ./nextjs-nginx

        ports:
            - 80:80

        volumes:
            - ./nextjs-nginx/conf:/etc/nginx/conf.d

    database:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default_authentication_plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        env_file:
            - database-docker-compose.env


volumes:
    django_static:
    django_media:
    mysql:
