version: '3.7'

services:
    nextjs:
        container_name: nextjs

        build: ./nextjs

        command: npm run dev

        volumes:
            - ./nextjs:/usr/src/nextjs

        ports:
            - 3000:3000

        depends_on:
          - django

    django:
        container_name: django

        build: ./django

        command: bash -c "python manage.py makemigrations && python manage.py migrate && python -u manage.py runserver 0.0.0.0:8000"

        volumes:
            - ./django:/usr/src/django

        env_file:
            - django-docker-compose.env

        environment:
            - DEBUG=1

        ports:
            - 8000:8000
