version: '3.7'

services:
    django:
            image: 303647508310.dkr.ecr.ap-northeast-1.amazonaws.com/animegatari-django:latest

            container_name: django

            build:
                context: ./django
                dockerfile: ./Dockerfile.build

            volumes:
                - ./django:/usr/src/django
                - django_static:/django/static
                - django_media:/django/media

            environment:
                # 1ならデバックモード
                - DEBUG=0
                # setting.pyに記載されているSECRET_KEYを記入
                - SECRET_KEY=django-insecure--w@!)fvdh72o8-wuwpa_(c00g(ew4t-t*#ghk+uwn^n%0fhce6

    nextjs:
        image: 303647508310.dkr.ecr.ap-northeast-1.amazonaws.com/animegatari-nextjs:latest

        container_name: nextjs

        build:
            context: ./nextjs
            dockerfile: ./Dockerfile.build

        volumes:
            - ./nextjs:/usr/src/nextjs


    nginx:
        image: 303647508310.dkr.ecr.ap-northeast-1.amazonaws.com/animegatari-nginx:latest

        container_name: nginx

        build: ./nginx

        ports:
            - 80:80

        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - django_static:/django/static
            - django_media:/django/media

volumes:
    django_static:
    django_media:
