# Generated by Django 3.2 on 2022-06-29 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendAnimeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='グループ名')),
                ('description', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='グループ説明')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_point', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='おすすめポイント')),
                ('anime', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reviewanime', verbose_name='おすすめしたいアニメ')),
                ('recommend_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recommendanimegroup', verbose_name='まとめるグループ')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
