# Generated by Django 3.2 on 2022-07-31 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220629_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendanimegroup',
            name='recommend_point',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='おすすめポイント'),
        ),
        migrations.AddField(
            model_name='recommendanimegroup',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='グループ管理ユーザー'),
        ),
        migrations.AddField(
            model_name='reviewanime',
            name='recommend_anime_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recommendanimegroup', verbose_name='おすすめしたいアニメ'),
        ),
        migrations.DeleteModel(
            name='RecommendAnime',
        ),
    ]
