# Generated by Django 3.2 on 2022-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220731_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='anime',
            field=models.ManyToManyField(blank=True, to='users.ReviewAnime', verbose_name='おすすめしたいアニメ'),
        ),
    ]
