# Generated by Django 3.2 on 2022-07-31 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_recommendanimegroup_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendanimegroup',
            name='anime',
        ),
        migrations.AddField(
            model_name='reviewanime',
            name='recommend_anime_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recommendanimegroup', verbose_name='おすすめしたいアニメ'),
        ),
    ]
