# Generated by Django 3.2 on 2022-07-31 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220731_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanime',
            name='recommend_anime_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.recommendanimegroup', verbose_name='レコメンドアニメグループ'),
        ),
    ]
