# Generated by Django 3.2 on 2022-07-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_reviewanime_recommend_anime_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewanime',
            name='recommend_anime_group',
        ),
        migrations.AddField(
            model_name='recommendanimegroup',
            name='anime',
            field=models.ManyToManyField(blank=True, to='users.ReviewAnime', verbose_name='レコメンドアニメ'),
        ),
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='グループ管理ユーザー'),
        ),
    ]
