# Generated by Django 3.2 on 2022-07-31 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220731_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='グループ管理ユーザー'),
        ),
    ]
