# Generated by Django 3.2 on 2022-02-22 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220222_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanime',
            name='star',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='レビューしたアニメの評価'),
        ),
    ]
