# Generated by Django 3.2 on 2022-02-22 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanime',
            name='star',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='レビューしたアニメの評価'),
        ),
    ]
