# Generated by Django 3.2 on 2022-07-31 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_recommendanimegroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='group_title',
            field=models.CharField(default='おすすめアニメ', max_length=40, null=True, verbose_name='グループタイトル'),
        ),
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理ユーザー'),
        ),
    ]
