# Generated by Django 3.2 on 2022-02-22 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_reviewanime_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewanime',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewanime',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
