# Generated by Django 3.2 on 2022-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220731_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendanimegroup',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='グループ概要'),
        ),
    ]
