# Generated by Django 3.2 on 2022-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_recommendanimegroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanime',
            name='comment',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='レビューコメント'),
        ),
    ]
