# Generated by Django 3.2 on 2022-07-31 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_reviewanime_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendanimegroup',
            name='favorite_count',
            field=models.ManyToManyField(blank=True, related_name='いいね数', to=settings.AUTH_USER_MODEL),
        ),
    ]
