# Generated by Django 3.2 on 2022-03-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_reviewanime_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewanime',
            constraint=models.UniqueConstraint(fields=('user', 'anime'), name='user_anime_unique'),
        ),
    ]
