# Generated by Django 3.2 on 2022-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reviewanime_user_anime_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_backImage',
            field=models.ImageField(blank=True, upload_to='user/backImage', verbose_name='ユーザーアイコン'),
        ),
    ]
