# Generated by Django 3.2 on 2022-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_user_backimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='自己紹介'),
        ),
    ]
