# Generated by Django 3.2 on 2022-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0025_remove_animedata_favoritecount'),
        ('users', '0021_profile_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_anime',
            field=models.ManyToManyField(blank=True, to='anime_data.AnimeData'),
        ),
    ]
