# Generated by Django 3.2 on 2022-03-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_icon',
        ),
    ]
