# Generated by Django 3.2 on 2022-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_profile_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userIcon',
            field=models.ImageField(blank=True, default='user/icon/デフォルトアイコン.png', upload_to='user/icon', verbose_name='ユーザーアイコン'),
        ),
    ]
