# Generated by Django 3.2 on 2022-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_profile_usericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_icon',
            field=models.ImageField(blank=True, default='デフォルトアイコン.png', upload_to='user/icon', verbose_name='ユーザーアイコン'),
        ),
    ]
