# Generated by Django 3.2 on 2022-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_backImage',
            field=models.ImageField(blank=True, default='user/backImage/デフォルト背景画像.jpg', upload_to='user/backImage', verbose_name='ユーザー背景画像'),
        ),
    ]
