# Generated by Django 3.2 on 2022-03-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_profile_user_backimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_introduction',
            field=models.CharField(default='', max_length=512, verbose_name='自己紹介'),
        ),
    ]
