# Generated by Django 3.2 on 2022-03-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0030_remove_animedata_favorite_count'),
        ('users', '0039_alter_profile_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime_data.animedata'),
        ),
    ]
