# Generated by Django 3.2 on 2022-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0030_remove_animedata_favorite_count'),
        ('users', '0040_customuser_favorite_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_anime',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_anime',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_count', to='anime_data.AnimeData'),
        ),
    ]
