# Generated by Django 3.2 on 2022-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(blank=True, null=True, verbose_name='シリーズ名')),
                ('nameEn', models.TextField(blank=True, null=True, verbose_name='シリーズ名EN')),
                ('nameRo', models.TextField(blank=True, null=True, verbose_name='シリーズ名RO')),
            ],
            options={
                'verbose_name_plural': 'AnimeSeriesData',
                'db_table': 'anime_series_db',
            },
        ),
        migrations.CreateModel(
            name='CharacterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.CharField(blank=True, max_length=191, null=True, verbose_name='キャラ名')),
                ('nameEn', models.TextField(blank=True, null=True, verbose_name='キャラ名EN')),
                ('nameKana', models.TextField(blank=True, null=True, verbose_name='キャラ名かな')),
                ('nickname', models.TextField(blank=True, null=True, verbose_name='ニックネーム')),
                ('nicknameEn', models.TextField(blank=True, null=True, verbose_name='ニックネームEN')),
                ('age', models.TextField(blank=True, null=True, verbose_name='年齢')),
                ('ageEn', models.TextField(blank=True, null=True, verbose_name='年齢EN')),
                ('birthday', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('birthdayEn', models.TextField(blank=True, null=True, verbose_name='誕生日EN')),
                ('bloodType', models.TextField(blank=True, null=True, verbose_name='血液型')),
                ('bloodTypeEn', models.TextField(blank=True, null=True, verbose_name='血液型EN')),
                ('height', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('heightEn', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('weight', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('weightEn', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('nationality', models.TextField(blank=True, null=True, verbose_name='国籍')),
                ('nationalityEn', models.TextField(blank=True, null=True, verbose_name='国籍EN')),
                ('occupation', models.TextField(blank=True, null=True, verbose_name='職業')),
                ('occupationEn', models.TextField(blank=True, null=True, verbose_name='職業EN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='キャラ紹介')),
                ('descriptionEn', models.TextField(blank=True, null=True, verbose_name='キャラ紹介EN')),
                ('descriptionSource', models.TextField(blank=True, null=True, verbose_name='キャラ紹介ソース')),
                ('descriptionSourceEn', models.TextField(blank=True, null=True, verbose_name='キャラ紹介ソースEN')),
                ('favoriteCharactersCount', models.IntegerField(blank=True, null=True, verbose_name='Annictユーザーお気に入り数')),
            ],
            options={
                'verbose_name_plural': 'CharacterData',
                'db_table': 'anime_character_db',
            },
        ),
        migrations.CreateModel(
            name='EpisodesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='第◯話')),
                ('numberText', models.TextField(blank=True, null=True, verbose_name='第◯話テキスト')),
                ('title', models.TextField(blank=True, null=True, verbose_name='エピソードタイトル')),
            ],
            options={
                'verbose_name_plural': 'EpisodesData',
                'db_table': 'anime_episodes_db',
            },
        ),
        migrations.CreateModel(
            name='GenreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('genre', models.CharField(max_length=50, unique=True, verbose_name='アニメジャンル')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.CharField(max_length=191, unique=True, verbose_name='声優名')),
                ('nameEn', models.TextField(blank=True, null=True, verbose_name='声優名EN')),
                ('nameKana', models.TextField(blank=True, null=True, verbose_name='声優名かな')),
                ('nickname', models.TextField(blank=True, null=True, verbose_name='ニックネーム')),
                ('nicknameEn', models.TextField(blank=True, null=True, verbose_name='ニックネームEN')),
                ('birthday', models.TextField(blank=True, null=True, verbose_name='誕生日')),
                ('bloodType', models.TextField(blank=True, null=True, verbose_name='血液型')),
                ('genderText', models.TextField(blank=True, null=True, verbose_name='性別')),
                ('height', models.TextField(blank=True, null=True, verbose_name='身長')),
                ('castsCount', models.IntegerField(blank=True, null=True, verbose_name='出演本数')),
                ('favoritePeopleCount', models.TextField(blank=True, null=True, verbose_name='Annictユーザーお気に入り数')),
            ],
            options={
                'verbose_name_plural': 'PersonData',
                'db_table': 'anime_person_db',
            },
        ),
        migrations.CreateModel(
            name='StaffsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(blank=True, null=True, verbose_name='スタッフ名')),
                ('roleOther', models.TextField(blank=True, null=True, verbose_name='職業')),
                ('roleOtherEn', models.TextField(blank=True, null=True, verbose_name='職業EN')),
            ],
            options={
                'verbose_name_plural': 'StaffsData',
                'db_table': 'anime_staffs_db',
            },
        ),
        migrations.CreateModel(
            name='CastsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('name', models.TextField(blank=True, null=True, verbose_name='声優名')),
                ('nameEn', models.TextField(blank=True, null=True, verbose_name='声優名EN')),
                ('sortNumber', models.IntegerField(blank=True, null=True, verbose_name='ソート番号')),
                ('character', models.ManyToManyField(to='anime_data.CharacterData')),
                ('person', models.ManyToManyField(to='anime_data.PersonData')),
            ],
            options={
                'verbose_name_plural': 'CastsData',
                'db_table': 'anime_casts_db',
            },
        ),
        migrations.CreateModel(
            name='AnimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('annictId', models.IntegerField(unique=True, verbose_name='AnnictId')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='タイトル')),
                ('titleEn', models.TextField(blank=True, null=True, verbose_name='タイトルEN')),
                ('titleKana', models.TextField(blank=True, null=True, verbose_name='タイトルかな')),
                ('titleRo', models.TextField(blank=True, null=True, verbose_name='タイトルRO')),
                ('media', models.TextField(blank=True, null=True, verbose_name='放送メディア')),
                ('episodesCount', models.IntegerField(blank=True, null=True, verbose_name='総エピソード数')),
                ('seasonName', models.TextField(blank=True, null=True, verbose_name='放送季節')),
                ('seasonYear', models.IntegerField(blank=True, null=True, verbose_name='放送年度')),
                ('watchersCount', models.IntegerField(blank=True, null=True, verbose_name='Annict視聴者数')),
                ('image', models.ImageField(default='/django/media/anime/thumbnail/NoImageサンプル画像.jpg', upload_to='anime/thumbnail')),
                ('story', models.TextField(blank=True, null=True, verbose_name='あらすじ')),
                ('casts', models.ManyToManyField(blank=True, to='anime_data.CastsData')),
                ('episodes', models.ManyToManyField(blank=True, to='anime_data.EpisodesData')),
                ('genres', models.ManyToManyField(blank=True, to='anime_data.GenreData')),
                ('seriesList', models.ManyToManyField(blank=True, to='anime_data.AnimeSeriesData')),
                ('staffs', models.ManyToManyField(blank=True, to='anime_data.StaffsData')),
            ],
            options={
                'verbose_name_plural': 'AnimeData',
                'db_table': 'anime_db',
            },
        ),
    ]
