# Generated by Django 3.2 on 2022-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='タイトル'),
        ),
    ]
