# Generated by Django 3.2 on 2022-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0002_alter_animedata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='annictId',
            field=models.IntegerField(verbose_name='AnnictId'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
