# Generated by Django 3.2 on 2022-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0003_auto_20220503_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='annictId',
            field=models.IntegerField(unique=True, verbose_name='AnnictId'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='タイトル'),
        ),
    ]
