# Generated by Django 3.2 on 2022-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0008_auto_20220120_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(max_length=50, verbose_name='アニメジャンル')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='animedata',
            name='tags',
        ),
        migrations.AddField(
            model_name='animedata',
            name='genre',
            field=models.ManyToManyField(to='anime_data.Genre'),
        ),
    ]
