# Generated by Django 3.2 on 2022-02-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0010_rename_genre_genredata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animedata',
            old_name='genre',
            new_name='genres',
        ),
    ]
