# Generated by Django 3.2 on 2022-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0011_rename_genre_animedata_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='casts',
            field=models.ManyToManyField(null=True, to='anime_data.CastsData'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='episodes',
            field=models.ManyToManyField(null=True, to='anime_data.EpisodesData'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='seriesList',
            field=models.ManyToManyField(null=True, to='anime_data.AnimeSeriesData'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='staffs',
            field=models.ManyToManyField(null=True, to='anime_data.StaffsData'),
        ),
    ]
