# Generated by Django 3.2 on 2022-02-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0014_auto_20220208_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='badCoount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='bad Count'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='genres',
            field=models.ManyToManyField(blank=True, to='anime_data.GenreData'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='goodCoount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Good Count'),
        ),
    ]
