# Generated by Django 3.2 on 2022-02-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0015_auto_20220208_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='badCoount',
            field=models.PositiveIntegerField(default=0, verbose_name='bad Count'),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='goodCoount',
            field=models.PositiveIntegerField(default=0, verbose_name='Good Count'),
        ),
    ]
