# Generated by Django 3.2 on 2022-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0016_auto_20220208_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animedata',
            old_name='badCoount',
            new_name='badCount',
        ),
        migrations.RenameField(
            model_name='animedata',
            old_name='goodCoount',
            new_name='goodCount',
        ),
    ]
