# Generated by Django 3.2 on 2022-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0017_auto_20220208_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='media',
            field=models.TextField(blank=True, null=True, verbose_name='放送メディア'),
        ),
    ]
