# Generated by Django 3.2 on 2022-02-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0020_animedata_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genredata',
            name='genre',
            field=models.CharField(max_length=50, unique=True, verbose_name='アニメジャンル'),
        ),
    ]
