# Generated by Django 3.2 on 2022-03-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0022_auto_20220222_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animedata',
            name='badCount',
        ),
    ]
