# Generated by Django 3.2 on 2022-03-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0023_remove_animedata_badcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animedata',
            old_name='goodCount',
            new_name='favoriteCount',
        ),
    ]
