# Generated by Django 3.2 on 2022-03-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0024_rename_goodcount_animedata_favoritecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animedata',
            name='favoriteCount',
        ),
    ]
