# Generated by Django 3.2 on 2022-03-25 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_data', '0025_remove_animedata_favoritecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='favorite_count',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
