# Generated by Django 3.2 on 2022-03-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0026_animedata_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='image',
            field=models.ImageField(default='/django/media/anime/thumbnail/NoImageサンプル画像.jpg', upload_to='anime/thumbnail'),
        ),
    ]
