# Generated by Django 3.2 on 2022-03-30 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_data', '0028_remove_animedata_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='favorite_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
