# Generated by Django 3.2 on 2022-03-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_data', '0029_animedata_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animedata',
            name='favorite_count',
        ),
    ]
